"""Persistence helpers for completed interview records."""

from .db import (
    DatabaseError,
    create_user,
    create_job,
    create_resume,
    create_tailored_resume,
    delete_user_interview,
    get_user_by_email,
    get_user_by_id,
    get_user_interview,
    get_user_interview_records,
    get_user_job,
    get_user_jobs,
    get_user_resume,
    get_user_resumes,
    get_user_tailored_resume,
    get_user_tailored_resumes,
    get_user_interviews,
    update_job_matching,
    init_database,
    save_completed_interview,
    update_resume_analysis,
)

__all__ = [
    "DatabaseError",
    "create_user",
    "create_job",
    "create_resume",
    "create_tailored_resume",
    "delete_user_interview",
    "get_user_by_email",
    "get_user_by_id",
    "get_user_interview",
    "get_user_interview_records",
    "get_user_job",
    "get_user_jobs",
    "get_user_resume",
    "get_user_resumes",
    "get_user_tailored_resume",
    "get_user_tailored_resumes",
    "get_user_interviews",
    "update_job_matching",
    "init_database",
    "save_completed_interview",
    "update_resume_analysis",
]
